### ISSUE TITLE
Remove nodejs dependency

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#3]
https://github.com/zeit/pkg

Should:
- [ ] Not require devs to have [nodejs](https://nodejs.org/en/) installed on their computer
- [ ] Not require internet access to start new project (currently runs `npm install`)
- [ ] Still be extensible via NPM 
- [ ] Still allow custom Gopack package to create `web_modules` for ESM

**Comment by jimafisk** [comment]
https://github.com/denoland/deno/issues/986

**Comment by jimafisk** [comment]
https://github.com/dgiagio/warp
https://github.com/nexe/nexe

**Comment by jimafisk** [comment]
https://github.com/tauri-apps/tauri/

**Comment by jimafisk** [comment]
https://www.reddit.com/r/golang/comments/gscbxb/compiling_svelte_with_go/

**Comment by jimafisk** [comment]
Based on reddit conversation, I'm thinking through how to run a V8 sandbox to compile svelte. Even though the actual script might not be faster than running node directly, I think it would speed up the build because we could cut out the `exec.Command` and the bundling (in Go) and unpacking (in JS)  of templates we're currently doing. It would also make installation easier which would resolve issues like https://github.com/plentico/plenti/issues/32 and we would no longer need to execute the system nodejs which should fix the snapcraft issue https://github.com/plentico/plenti/issues/31.

V8go can't require/import other scripts (see https://github.com/rogchap/v8go/issues/22) so we'll have to rethink a couple of things:
1. Writing to the filesystem will have to be handed back over to Go, which is desired because it will likely be faster.
2. We'll need to bundle dependencies (like svelte) using something like esbuild (https://github.com/evanw/esbuild)

**Comment by jimafisk** [comment]
Watching for a Go API on esbuild: https://github.com/evanw/esbuild/issues/152

**Comment by jimafisk** [comment]
Esbuild Go API docs: https://github.com/evanw/esbuild/blob/master/docs/go-api.md

**Comment by jimafisk** [comment]
Proposal:
1. Bundle up the 4 NPM dependencies required by Plenti core (navaid, regexparam, require-relative, svelte) and put them as defaults in the binary using go:generate. Possibly can remove require-relative since it's part of the node build process that will likely get replaced by Go code.
2. When creating a new project (`plenti new site my-site`) plenti will write these dependencies to `/node_modules/` folder inside the project.
3. If a collaborator pulls down an existing project, they will not be running the `plenti new site` command. So `plenti build` and `plenti serve` must check for the existence of a `/node_modules/` folder and if it's not there, write the defaults included with the binary to the filesystem. This check is necessary since the `/node_modules/` folder is not typically tracked by git. 
4. The build will use the esbuild bundler to pull all the dependencies together (mainly the svelte compiler) so that we can compile the site using v8go.

Things to keep in mind:
1. If you have modified the `/node_modules/`, either to extend your site with additional functionality or to simply change the version of a core dependency, this should be reflected in your `package-lock.json` file. It is now your responsibility to communicate with your team that using NPM like normal is required (e.g. when pulling an existing project, if you simply `plenti serve` you are going to get the defaults, you should instead `npm install` first).
2. The check for the existence of the `/node_modules/` folder will not inspect versions or individual packages inside the `/node_modules/` folder, it will simply check that the `/node_modules/` folder exists - so if you've added this folder and removed a core package, it will break the build.
3. If you've customized the `/node_modules/` in any way (extended or updated), you will need to account for this in the CI that builds and deploys your site. Basically you will need to add an `npm install` step. Currently the official plenti image (https://hub.docker.com/r/plentico/plenti) does not have nodejs or npm installed on it, so you will need to take care of setting up that. In the future we'd like to support a second container with NPM on it already to make this easier, but we'll keep it separate to avoid bloat on the official image for folks who want a faster experience when using plenti core without modification.

**Comment by jimafisk** [comment]
We can remove [require-relative](https://github.com/kamicane/require-relative) by just pulling the part we need into `build.js`, however it still requires referencing the `module` nodejs package:
 
```js
import Module from 'module';

let root = new Module('/home/jimafisk/Desktop/my-site/@root');
root.filename = '/home/jimafisk/Desktop/my-site/@root';
root.paths = Module._nodeModulePaths('/home/jimafisk/Desktop/my-site');
let htmlWrapper = '/home/jimafisk/Desktop/my-site/layout/global/html.svelte';
let component = root.require(htmlWrapper).default;
```

**Comment by jimafisk** [comment]
The current implementation using [v8go](https://github.com/rogchap/v8go) is working for the client build, but it might be worth looking into [QuickJS](https://bellard.org/quickjs/) for speed improvements and module support:
- https://www.reddit.com/r/golang/comments/ho0o9e/go_bindings_to_quickjs_a_fast_small_and/
- https://github.com/lithdew/quickjs
- https://github.com/wspl/go-quickjs
- https://github.com/alexsunday/quickjs

Another conversation recommending QuickJS: https://www.reddit.com/r/golang/comments/cd5gja/does_anyone_have_experience_with_parsing/

**Comment by jimafisk** [comment]
Tried some rough benchmarking of [QuickJS](https://github.com/lithdew/quickjs) against [v8go](https://github.com/rogchap/v8go):

| QuickJS  | v8go |
| ------------- | ------------- |
| 649.606009ms  | 53.061618ms  |
| 686.947327ms  | 61.719715ms  |
| 673.800305ms  | 60.363899ms  |
| 670.392486ms  | 57.559065ms  |
| 673.398664ms  | 57.768148ms  |
| 683.323302ms  | 60.482449ms  |

<details>
<summary>Code Used</summary>

```go
package main

import (
	"fmt"
	"time"

	"github.com/lithdew/quickjs"
	"rogchap.com/v8go"
)

func main() {
	start := time.Now()
	rt := quickjs.NewRuntime()
	ctx := rt.NewContext()
	result, err := ctx.Eval(`
	function factorial(n) {
		return n === 1 ? n : n * factorial(--n);
	}
	
	var i = 0;
	
	while (i++ < 1e6) {
		factorial(10);
	}
	`)
	if err != nil {
		fmt.Printf("Eval error: %v", err)
	}
	fmt.Println(result.String())
	elapsed := time.Since(start)
	fmt.Println(elapsed)

	start = time.Now()
	vm, _ := v8go.NewIsolate()
	ctx1, _ := v8go.NewContext(vm)
	result1, err1 := ctx1.RunScript(`
	function factorial(n) {
		return n === 1 ? n : n * factorial(--n);
	}
	
	var i = 0;
	
	while (i++ < 1e6) {
		factorial(10);
	}
	`, "math.js")
	if err1 != nil {
		fmt.Printf("Eval error: %v", err1)
	}
	fmt.Println(result1)
	elapsed = time.Since(start)
	fmt.Println(elapsed)
}
```

</details>

**Comment by jimafisk** [comment]
Wrapping my head around process for creating static html.

<details>
<summary>A simplified version of how we're getting static HTML using NodeJS looks something like this (click to reveal)</summary>

<br>

<details>
<summary>Example staticBuildStr format</summary>

```json
[
  {
    "node": { 
      "path": "/blog/adding_pletiform",
      "type": "blog",
      "filename": "adding_pletiform.json",
      "fields": {
        "title": "Build sites with good form",
        "body": [ "Need an easy webform solution?", "Try adding a <a href='https://plentiform.com' target='blank' rel='noopener noreferrer'>plentiform</a>! (Coming soon)" ],
        "author": "Jim Fisk",
        "date": "1/26/2020"
      }
    }, 
    "componentPath": "layout/content/blog.svelte",
    "destPath": "public//blog/adding_pletiform/index.html"
  },
  ...
]
```
</details>

```js
import 'svelte/register.js';

let htmlWrapper = path.join(path.resolve(), 'layout/global/html.svelte')
let root = new Module();
let component = root.require(htmlWrapper).default;

let staticBuildStr = JSON.parse(args[0]); // See example format above
staticBuildStr.forEach(arg => {
  const route = root.require(arg.componentPath).default;
  let props = {
    route: route,
    node: arg.node
  }
  let { html, css } = component.render(props);
}
```

</details>

What's actually happening behind the scenes is it looks like `node_modules/svelte/register.js` actually imports `node_modules/svelte/compiler.js` then runs a `svelte.compile()` passing the `generate: 'ssr'` option. It then wraps the `js.code` outputted in a CJS module using `module._compile()`. 

Manually running the svelte compiler with SSR as a test in plenti's `cmd/build/client.go`:
```go
ctx.RunScript("var { js, css } = svelte.compile(`"+componentStr+"`, {generate: 'ssr'});", "compile_svelte")
jsCode, _ := ctx.RunScript("js.code;", "compile_svelte")
fmt.Println(jsCode)
```

<details>
<summary>Returns SSR components that look like this (click to reveal)</summary>

```
/* generated by Svelte v3.23.2 */
import { create_ssr_component } from "svelte/internal";

const sortByDate = (items, order) => {
	items.sort((a, b) => {
		// Must have a field specifically named "date" to work.
		// Feel free to extend to other custom named date fields.
		if (a.fields.hasOwnProperty("date") && b.fields.hasOwnProperty("date")) {
			let aDate = new Date(a.fields.date);
			let bDate = new Date(b.fields.date);

			if (order == "oldest") {
				return aDate - bDate;
			}

			return bDate - aDate;
		}
	});

	return items;
};

const Component = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	return ``;
});

export default Component;
export { sortByDate };
```
</details>

Notably each starts with an `import { create_ssr_component } from "svelte/internal";` ESM.

If you look at `node_modules/svelte/internal/index.js` it runs the `create_ssr_component()` function on line 1317, which is where you get the `$$render` functions. This ties back to the first snippet in this comment where:
```js
let component = root.require(htmlWrapper).default;
console.log(component);
```

Yields the following value: 
```
{ render: [Function: render], '$$render': [Function: $$render] }
```

**Comment by jimafisk** [comment]
Using v8go instead of Node is getting a lot closer, but there are persistent issues. One of those is importing components with custom names. Right now we add SSR compiled JS to the ctx for each component. We don't have a smart way of doing this so we're simply naming based on the filename (e.g. nav.svelte becomes Nav, pages.svelte becomes Pages, etc). This does not account for importing a component with a custom name, for instance the default starter does something like this: `import Uses from "../components/template.svelte";`.

One solution is when reading the layout file, check for imports and when found assign the aliased name to the base component in the ctx. So using the above example:

```go
SSRctx.RunScript("var Uses = Template", "create_ssr")
```

<details>
<summary>Whiteboard visualization</summary>

![IMG_20200716_130347203](https://user-images.githubusercontent.com/5913244/87703475-ed4d1700-c768-11ea-82d3-663714e03fb7.jpg)

</details>

The downside is you would have a naming collision if different pages used the same alias for different components.

A more robust solution might be isolating the ctx to the current component and its specific imports using a custom gopack-like lookup. Would need to consider the performance implications of setting something like this up. Currently the v8go implementation is roughly as fast as the node implementation. I'll do some benchmarking once this is a little more stable.

**Comment by jimafisk** [comment]
New thought: give each component a signature based on its path and use that as the variable name where it's declared and everywhere it's referenced, e.g. `layout/components/grid.svelte` would become `var layout_components_grid;`. That will avoid any trouble with two components with the same name in different folders, which is actually a different naming collision issue than what was mentioned in the previous comment.

When reading the file we will have to analyze relative paths (e.g. `../components/grid.svelte`) to get the full path from root. Then change whatever it is imported as to the signature. Taking a different example:

<details>
<summary>Before converting</summary>

```js
/* generated by Svelte v3.23.2 */
import {
	create_ssr_component,
	each,
	escape,
	validate_component
} from "svelte/internal";

import Uses from "../components/template.svelte";

const Component = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { title } = $$props, { description } = $$props;
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);

	return `<h1>${escape(title)}</h1>

<div>${each(description, paragraph => `<p>${paragraph}</p>`)}</div>

${validate_component(Uses, "Uses").$$render($$result, { type: "pages" }, {}, {})}

<p><a href="${"/"}">Back home</a></p>`;
});

export default Component;
```

</details>

<details>
<summary>After converting</summary>

```js
/* generated by Svelte v3.23.2 */
/*import {
	create_ssr_component,
	each,
	escape,
	validate_component
} from "svelte/internal";*/

/*import Uses from "../components/template.svelte";*/

var layout_content_pages = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { title } = $$props, { description } = $$props;
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);

	return `<h1>${escape(title)}</h1>

<div>${each(description, paragraph => `<p>${paragraph}</p>`)}</div>

${validate_component(layout_components_template, "layout_component_template").$$render($$result, { type: "pages" }, {}, {})}

<p><a href="${"/"}">Back home</a></p>`;
});

/*export default Component;*/
```

</details>

Note we comment out the import/export statements in the SSR'd JS because v8go can't handle it. We essentially bundle the dependencies together manually in the vm ctx. 

For the same example above, here is the Template component that is being imported:

<details>
<summary>Before being converted</summary>

```js
/* generated by Svelte v3.23.2 */
import {
	add_attribute,
	create_ssr_component,
	escape,
	null_to_empty
} from "svelte/internal";

const css = {
	code: ".template.svelte-kyi9jr{display:flex;align-items:center}pre.svelte-kyi9jr{display:flex;padding-left:5px}code.svelte-kyi9jr{background-color:var(--base);padding:5px 10px}code.copied.svelte-kyi9jr{background-color:var(--accent)}button.svelte-kyi9jr{border:1px solid rgba(0,0,0,.1);background:white;padding:4px;border-top-right-radius:5px;border-bottom-right-radius:5px;cursor:pointer}",
	map: "{\"version\":3,\"file\":null,\"sources\":[null],\"sourcesContent\":[\"<script>\\n  export let type;\\n\\n  let path;\\n  let copyText = \\\"Copy\\\";\\n  var copy = async () => {\\n    if (!navigator.clipboard) {\\n      return\\n    }\\n    try {\\n      copyText = \\\"Copied\\\";\\n      await navigator.clipboard.writeText(path.innerHTML);\\n      setTimeout(() => copyText = \\\"Copy\\\", 500);\\n    } catch (err) {\\n      console.error('Failed to copy!', err)\\n    }\\n  }\\n</script>\\n\\n<div class=\\\"template\\\">\\n  <span>Template:</span>\\n  <pre>\\n    <code bind:this={path} class=\\\"{copyText}\\\">layout/content/{type}.svelte</code>\\n    <button on:click={copy}>{copyText}</button>\\n  </pre>\\n</div>\\n\\n<style>\\n  .template {\\n    display: flex;\\n    align-items: center;\\n  }\\n  pre {\\n    display: flex;\\n    padding-left: 5px;\\n  }\\n  code {\\n      background-color: var(--base);\\n      padding: 5px 10px;\\n  }\\n  code.copied {\\n      background-color: var(--accent);\\n  }\\n  button {\\n    border: 1px solid rgba(0,0,0,.1);\\n    background: white;\\n    padding: 4px;\\n    border-top-right-radius: 5px;\\n    border-bottom-right-radius: 5px;\\n    cursor: pointer;\\n  }\\n</style>\"],\"names\":[],\"mappings\":\"AA4BE,SAAS,cAAC,CAAC,AACT,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,AACrB,CAAC,AACD,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,GAAG,AACnB,CAAC,AACD,IAAI,cAAC,CAAC,AACF,gBAAgB,CAAE,IAAI,MAAM,CAAC,CAC7B,OAAO,CAAE,GAAG,CAAC,IAAI,AACrB,CAAC,AACD,IAAI,OAAO,cAAC,CAAC,AACT,gBAAgB,CAAE,IAAI,QAAQ,CAAC,AACnC,CAAC,AACD,MAAM,cAAC,CAAC,AACN,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC,CAChC,UAAU,CAAE,KAAK,CACjB,OAAO,CAAE,GAAG,CACZ,uBAAuB,CAAE,GAAG,CAC5B,0BAA0B,CAAE,GAAG,CAC/B,MAAM,CAAE,OAAO,AACjB,CAAC\"}"
};

const Component = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type } = $$props;
	let path;
	let copyText = "Copy";

	var copy = async () => {
		if (!navigator.clipboard) {
			return;
		}

		try {
			copyText = "Copied";
			await navigator.clipboard.writeText(path.innerHTML);
			setTimeout(() => copyText = "Copy", 500);
		} catch(err) {
			console.error("Failed to copy!", err);
		}
	};

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css);

	return `<div class="${"template svelte-kyi9jr"}"><span>Template:</span>
  <pre class="${"svelte-kyi9jr"}"><code class="${escape(null_to_empty(copyText)) + " svelte-kyi9jr"}"${add_attribute("this", path, 1)}>layout/content/${escape(type)}.svelte</code>
    <button class="${"svelte-kyi9jr"}">${escape(copyText)}</button></pre>
</div>`;
});

export default Component;
```

</details>

<details>
<summary>After being converted</summary>

```js
/* generated by Svelte v3.23.2 */
/*import {
	add_attribute,
	create_ssr_component,
	escape,
	null_to_empty
} from "svelte/internal";*/

var css = {
	code: ".template.svelte-kyi9jr{display:flex;align-items:center}pre.svelte-kyi9jr{display:flex;padding-left:5px}code.svelte-kyi9jr{background-color:var(--base);padding:5px 10px}code.copied.svelte-kyi9jr{background-color:var(--accent)}button.svelte-kyi9jr{border:1px solid rgba(0,0,0,.1);background:white;padding:4px;border-top-right-radius:5px;border-bottom-right-radius:5px;cursor:pointer}",
	map: "{\"version\":3,\"file\":null,\"sources\":[null],\"sourcesContent\":[\"<script>\\n  export let type;\\n\\n  let path;\\n  let copyText = \\\"Copy\\\";\\n  var copy = async () => {\\n    if (!navigator.clipboard) {\\n      return\\n    }\\n    try {\\n      copyText = \\\"Copied\\\";\\n      await navigator.clipboard.writeText(path.innerHTML);\\n      setTimeout(() => copyText = \\\"Copy\\\", 500);\\n    } catch (err) {\\n      console.error('Failed to copy!', err)\\n    }\\n  }\\n</script>\\n\\n<div class=\\\"template\\\">\\n  <span>Template:</span>\\n  <pre>\\n    <code bind:this={path} class=\\\"{copyText}\\\">layout/content/{type}.svelte</code>\\n    <button on:click={copy}>{copyText}</button>\\n  </pre>\\n</div>\\n\\n<style>\\n  .template {\\n    display: flex;\\n    align-items: center;\\n  }\\n  pre {\\n    display: flex;\\n    padding-left: 5px;\\n  }\\n  code {\\n      background-color: var(--base);\\n      padding: 5px 10px;\\n  }\\n  code.copied {\\n      background-color: var(--accent);\\n  }\\n  button {\\n    border: 1px solid rgba(0,0,0,.1);\\n    background: white;\\n    padding: 4px;\\n    border-top-right-radius: 5px;\\n    border-bottom-right-radius: 5px;\\n    cursor: pointer;\\n  }\\n</style>\"],\"names\":[],\"mappings\":\"AA4BE,SAAS,cAAC,CAAC,AACT,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,AACrB,CAAC,AACD,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,IAAI,CACb,YAAY,CAAE,GAAG,AACnB,CAAC,AACD,IAAI,cAAC,CAAC,AACF,gBAAgB,CAAE,IAAI,MAAM,CAAC,CAC7B,OAAO,CAAE,GAAG,CAAC,IAAI,AACrB,CAAC,AACD,IAAI,OAAO,cAAC,CAAC,AACT,gBAAgB,CAAE,IAAI,QAAQ,CAAC,AACnC,CAAC,AACD,MAAM,cAAC,CAAC,AACN,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC,CAChC,UAAU,CAAE,KAAK,CACjB,OAAO,CAAE,GAAG,CACZ,uBAAuB,CAAE,GAAG,CAC5B,0BAA0B,CAAE,GAAG,CAC/B,MAAM,CAAE,OAAO,AACjB,CAAC\"}"
};

var layout_components_template = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { type } = $$props;
	let path;
	let copyText = "Copy";

	var copy = async () => {
		if (!navigator.clipboard) {
			return;
		}

		try {
			copyText = "Copied";
			await navigator.clipboard.writeText(path.innerHTML);
			setTimeout(() => copyText = "Copy", 500);
		} catch(err) {
			console.error("Failed to copy!", err);
		}
	};

	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	$$result.css.add(css);

	return `<div class="${"template svelte-kyi9jr"}"><span>Template:</span>
  <pre class="${"svelte-kyi9jr"}"><code class="${escape(null_to_empty(copyText)) + " svelte-kyi9jr"}"${add_attribute("this", path, 1)}>layout/content/${escape(type)}.svelte</code>
    <button class="${"svelte-kyi9jr"}">${escape(copyText)}</button></pre>
</div>`;
});

/*export default Component;*/
```

</details>

**Comment by jimafisk** [comment]
When client and static builds were separate (https://github.com/plentico/plenti/commit/c40c1d55d0f8e1751580fa41062387aa1b83a5eb):
- client: https://github.com/plentico/plenti/blob/c40c1d55d0f8e1751580fa41062387aa1b83a5eb/defaults/layout/ejected/build_client.js
- static: https://github.com/plentico/plenti/blob/c40c1d55d0f8e1751580fa41062387aa1b83a5eb/defaults/layout/ejected/build_static.js

The go build compiled components and static html individually:
- components: https://github.com/plentico/plenti/blob/c40c1d55d0f8e1751580fa41062387aa1b83a5eb/cmd/build/client.go
- static html (not finished): https://github.com/plentico/plenti/blob/c40c1d55d0f8e1751580fa41062387aa1b83a5eb/cmd/build/static.go

**Comment by jimafisk** [comment]
Benchmarking:

| Attempt # | Node  | No Node |
| ----- | ------------- | ------------- |
| 1 | 649.606009ms  | 53.061618ms  |
| 2 | 686.947327ms  | 61.719715ms  |
| 3 | 673.800305ms  | 60.363899ms  |
| 4 | 670.392486ms  | 57.559065ms  |
| 5 | 673.398664ms  | 57.768148ms  |
| 6 | 683.323302ms  | 60.482449ms  |
| 6 | 683.323302ms  | 60.482449ms  |
| 6 | 683.323302ms  | 60.482449ms  |
| 6 | 683.323302ms  | 60.482449ms  |

**Comment by jimafisk** [comment]
In [this hacker news thread](https://news.ycombinator.com/item?id=21376557) leaveyou wrote: 
> Please someone make a Svelte compiler in Go.. I can't stand Node.js and I can't install it on my machine without feeling dirty.

batisteo responded with:
> There’s a decent JS to JS compiler (replacement of Babel) in Rust which understand TypeScript: https://swc-project.github.io

I remember looking into SWC early on, but doesn't seem like it made it onto this thread for some reason. I have some concerns about the amount of processing we're having to do to run everything in v8, but probably not going to make any switches in the short term. If there was a Svelte compiler written in Go with an API it would make things faster and more consistent for this project. It would also be nice not to require CGO so we could start cross compiling for Windows again.

**Comment by zaydek** [comment]
@jimafisk I just caught your talk on creating a Go SSG for Svelte: https://www.youtube.com/watch?v=4tD3Jz7JUfk, I’m about halfway through. I thought I’d comment here because you and I seem to be interested in the same problem space, I even tried making a SSG for React and just gave up and decided Svelte is the future. This is as far as I got: https://github.com/zaydek/retro.

I figured out how to solve for these problems:
- Using a [Makefile](https://github.com/zaydek/retro/blob/master/Makefile#L65) to simplify cross-platform compilation
- [Using NPM for distribution](https://github.com/zaydek/retro/blob/master/Makefile#L85) (I think you’re shipping a CLI binary, not sure)
- Using esbuild as a bundler
- Page-based routing
- Resolving / caching props on the server (e.g. getStaticProps or whatever in Next.js / Remix Run)
- Etc.

All that being said, I realized React is actually very problematic as the frontend target because it’s so reliant on Babel / ESLint, etc. that even if you solve the backend problem, you still have the whole DX problem which is significant and I don’t care enough about to solve simultaneously.

So I thought I’d leave a comment here to get your attention and see if you want to connect. 🙂 Feel free to email me at zaydekdotcom [at] gmail or DM me on Twitter @username_ZAYDEK. I couldn’t easily find your email so I thought I’d just comment here. 😬

Solid work you got going on here.

**Comment by jimafisk** [comment]
Retro looks cool @zaydek! I'd love to connect, just followed you on twitter and sent you an email :)

**Comment by jimafisk** [comment]
I took another look at a pure Golang javascript interpreter to see if it was feasible to drop the complexities that come with a cgo dependency. Currently it does seem like that would come at a significant performance cost.

Rough benchmarking of [Goja](https://github.com/dop251/goja) against [v8go](https://github.com/rogchap/v8go):

| Attempt # | Goja  | v8go |
| ----- | ------------- | ------------- |
| 1 | 3.222790268s  | 56.900828ms  |
| 2 | 3.16795169s  | 56.840583ms  |
| 3 | 3.228237879s  | 57.287548ms  |
| 4 | 3.262925706s  | 57.178266ms  |
| 5 | 3.188262189s  | 56.869266ms  |

<details>
<summary>Benchmarking code</summary>
<br>

```go
package main

import (
  "fmt"
  "time"

  "github.com/dop251/goja"
  "rogchap.com/v8go"
)

func main() {
  start := time.Now()
  gojavm := goja.New()
  result, err := gojavm.RunString(`
  function factorial(n) {
    return n === 1 ? n : n * factorial(--n);
  }
  
  var i = 0;
  
  while (i++ < 1e6) {
    factorial(10);
  }
  `)
  if err != nil {
    fmt.Printf("Goja error: %v", err)
  }
  if result.Export().(int64) == 3628800 {
    elapsed := time.Since(start)
    fmt.Println(elapsed)
  }

  start = time.Now()
  vm, _ := v8go.NewIsolate()
  ctx1, _ := v8go.NewContext(vm)
  result1, err1 := ctx1.RunScript(`
  function factorial(n) {
    return n === 1 ? n : n * factorial(--n);
  }
  
  var i = 0;
  
  while (i++ < 1e6) {
    factorial(10);
  }
  `, "math.js")
  if err1 != nil {
    fmt.Printf("Eval error: %v", err1)
  }
  if result1.String() == "3628800" {
    elapsed := time.Since(start)
    fmt.Println(elapsed)
  }
}
```

</details>

From Goja's README:

> Although it's faster than many scripting language implementations in Go I have seen (for example it's 6-7 times faster than otto on average) it is not a replacement for V8 or SpiderMonkey or any other general-purpose JavaScript engine.

Running a factorial like the example used for the benchmark is a heavy computation:

> If most of the work is done in javascript (for example crypto or any other heavy calculations) you are definitely better off with V8.

The typical Plenti site might be lighter on computational requirements. If down the road we start moving Svelte compiling features into Go, there's a chance the performance between these projects would even out a bit:

> If you need a scripting language that drives an engine written in Go so that you need to make frequent calls between Go and javascript passing complex data structures then the cgo overhead may outweigh the benefits of having a faster javascript engine.

Another consideration would be full ES6 compatibility: https://github.com/dop251/goja/milestone/1?closed=1

**Comment by jimafisk** [comment]
Also took a quick look at https://github.com/gojisvm/gojis, but the docs are still WIP (https://gojisvm.github.io/api.html) so it would need to mature before evaluating more seriously.

Tried running the Svelte compiler.js inside Goja with es6 support: `go get github.com/dop251/goja@es6`. Unfortunately it does not seem to have support for block scoped variables like `const` and `let`: https://github.com/dop251/goja/issues/167#issuecomment-660967321

<details>
<summary>Test Goja code</summary>
<br>

```go
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/dop251/goja"
)

func main() {
	compiler, err := ioutil.ReadFile("compiler.js")
	if err != nil {
		fmt.Println("Can't read compiler.js")

	}
	vm := goja.New()
	result, err := vm.RunScript("test", string(compiler))
	if err != nil {
		fmt.Printf("Goja error: %v", err)
	}
	println(result.Export())
}
```

</details>

<details>
<summary>Error message</summary>

```
Goja error: SyntaxError: test: Line 7:2 Unexpected reserved word (and 14443 more errors)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x702239]

goroutine 1 [running]:
main.main()
        /home/jimafisk/Desktop/benchmarks/test.go:24 +0x219
```

</details>

----

In case it's useful, here's what you currently get out of the box with Plenti for build times:

<details>
<summary>Default "learner" starter with v8go build benchmarks (ran 15 times individually)</summary>
<br>

- 993.95377ms
- 888.726728ms
- 983.571047ms
- 953.345185ms
- 1.063483094s
- 918.495382ms
- 961.942967ms
- 944.106465ms
- 953.192401ms
- 968.931752ms
- 968.555285ms
- 1.069975253s
- 1.088950308s
- 974.294567ms
- 993.814659ms

</details>

**Comment by jimafisk** [comment]
It seems like [Goja](https://github.com/dop251/goja) has come a long way since I last tested it. The [ES6 milestone](https://github.com/dop251/goja/milestone/1?closed=1) has been completed and I ran some performance tests against [v8go](https://github.com/rogchap/v8go) again and the results were very different from last time:

| Attempt # | Script Size | Goja | V8go |
|--------------|----------------|--------|---------|
| 1 | Big | 163ns :pinching_hand: | 161ns :heavy_check_mark: |
| 1 | Small | 167ns :heavy_check_mark: | 180ns |
| 2 |  Big | 174ns | 146ns :heavy_check_mark: |
| 2 | Small | 250ns | 175ns :heavy_check_mark: | 
| 3 | Big | 245ns | 182ns :heavy_check_mark: |
| 3 | Small | 179ns :pinching_hand: | 175ns :heavy_check_mark: | 
| 4 | Big | 179ns | 157ns :heavy_check_mark: |
| 4 | Small | 234ns | 175ns :heavy_check_mark: |
| 5 | Big | 172ns | 148ns :heavy_check_mark: |
| 5 | Small | 252ns | 170ns :heavy_check_mark: |
| 6 | Big | 235ns | 164ns :heavy_check_mark: |
| 6 | Small | 171ns :heavy_check_mark: | 182ns |
| 7 | Big | 168ns :heavy_check_mark: | 173ns :pinching_hand: |
| 7 | Small | 149ns | 131ns :heavy_check_mark: |
| 8 | Big | 152ns :heavy_check_mark: | 163ns |
| 8 | Small | 168ns | 138ns :heavy_check_mark: |
| 9 | Big | 141ns :pinching_hand: | 139ns :heavy_check_mark: |
| 9 | Small | 169ns :heavy_check_mark: | 239ns |
| 10 | Big | 158ns | 151ns :heavy_check_mark: |
| 10 | Small | 154ns :heavy_check_mark: | 159ns :pinching_hand: |

:pinching_hand: = within 5ns

So the numbers are much closer, in some cases goja even comes out ahead. My next step is to try using it to actually compile some svelte components and see how that goes. 

<details>
<summary>Benchmarking code</summary>

```go
package main

import (
	"fmt"
	"time"

	"github.com/dop251/goja"

	"rogchap.com/v8go"
)

func main() {
	js1 := `
function factorial(n) {
	return n === 1 ? n : n * factorial(--n);
}	
var i = 0;	
while (i++ < 1e6) {
	factorial(10);
}`
	js2 := `
function factorial(n) {
	return n === 1 ? n : n * factorial(--n);
}
var i = 0;
while (i++ < 10) {
	factorial(10);
}`
	runV8go(js1)
	runGoja(js1)

	runV8go(js2)
	runGoja(js2)
}

func runGoja(js string) {
	elapsed := time.Since(time.Now())
	vm := goja.New()
	v, err := vm.RunString(js)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Print(v)
	fmt.Printf(" goja " + elapsed.String() + "\n")
}

func runV8go(js string) {
	elapsed := time.Since(time.Now())
	vm, _ := v8go.NewContext(nil)
	v, err := vm.RunScript(js, "")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Print(v)
	fmt.Printf(" v8 " + elapsed.String() + "\n")
}
```

</details>
